name: Build and deploy
on:
  push: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - aarch64
          - i686
          - x86_64
    steps:
      - uses: actions/checkout@v2
      - name: docker qemu multi-arch
        if: matrix.arch != 'x86_64'
        run: |
          sudo apt-get update -q -y
          sudo apt-get -qq install -y binfmt-support qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
      - name: appimage
        run: |
          SOURCE_DATE_EPOCH=$(git show -s --format=%ct) ./build.sh ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: appimage-${{ matrix.arch }}
          path: build/*.AppImage
