name: Build and deploy
on:
  push: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          - i686
          - x86_64
    steps:
      - uses: actions/checkout@v4
      - name: docker qemu multi-arch
        if: matrix.arch != 'x86_64'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
      - name: appimage
        run: |
          SOURCE_DATE_EPOCH=$(git show -s --format=%ct) ./build.sh ${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        with:
          name: appimage-${{ matrix.arch }}
          path: dist/*.AppImage
  deploy:
    name: Deploy
    needs:
      - build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p dist
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - run: ./deploy.sh dist/**/*.AppImage
        env:
          RELEASES_API_KEY: ${{ secrets.GITHUB_TOKEN }}
