name: Build and deploy
on:
  push: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - i686
          - x86_64
    steps:
      - uses: actions/checkout@v2
      - name: appimage
        run: |
          SOURCE_DATE_EPOCH=$(git show -s --format=%ct) ./build.sh ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: appimage-${{ matrix.arch }}
          path: build/*.AppImage
